variables:
  CACHE_DIR: "$CI_PROJECT_DIR/build"
  CACHE_DIR2: "$CI_PROJECT_DIR/.gradle"
  
  ORIG_ARTIFACTS: "$CI_PROJECT_DIR/build/libs/WGBlockReplacer-*.jar"
  ARTIFACTS: "$CI_PROJECT_DIR/WGBlockReplacer-*.jar"

cache:
 paths:
 - $CACHE_DIR
 - $CACHE_DIR2
 key: "$CI_BUILD_REF_NAME"
 untracked: false

stages:
- deploy
    
deploy:
  stage: deploy
  script:
  - ./gradlew clean build curseforge -PcurseForgeApiKey=$curseForgeApiKey
  - cp $ORIG_ARTIFACTS .
  when: manual
  artifacts:
    name: "WGBlockReplacer-$(cat $CACHE_DIR/.version)"
    paths:
    - $ARTIFACTS
    
deployMaven:
  stage: deploy
  script:
  - ./gradlew clean build uploadArchives curseforge -PcurseForgeApiKey=$curseForgeApiKey
  - cp $ORIG_ARTIFACTS .
  when: manual
  artifacts:
    name: "WGBlockReplacer-$(cat $CACHE_DIR/.version)"
    paths:
    - $ARTIFACTS
