modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/The-Fireplace-Minecraft-Mods/Block-Replacer/issues"
displayURL="https://minecraft.curseforge.com/projects/wg-block-replacer"
credits=""
authors="The_Fireplace"

[[mods]]
modId="wgblockreplacer"
version="${file.jarVersion}"
displayName="WorldGen Block Replacer"
description='''
Allows you to replace blocks in your world generation with other blocks.
'''

[[dependencies.wgblockreplacer]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.wgblockreplacer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2,1.14)"
    ordering="NONE"
    side="SERVER"